// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-gateway/internal/biz"
	"api-gateway/internal/conf"
	"api-gateway/internal/data"
	"api-gateway/internal/logger"
	"api-gateway/internal/server"
	"api-gateway/internal/service"
	"github.com/go-kratos/kratos/v2"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data) (*kratos.App, func(), error) {
	logLogger, cleanup, err := logger.NewZapLogger()
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, logLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logLogger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logLogger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logLogger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logLogger)
	app := newApp(logLogger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
